# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('discri', models.CharField(max_length=80)),
                ('tem', models.BooleanField(default=True)),
                ('hum', models.BooleanField(default=True)),
                ('pm25', models.BooleanField(default=True)),
                ('pm10', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('realname', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tem', models.BooleanField(default=True)),
                ('hum', models.BooleanField(default=True)),
                ('pm25', models.BooleanField(default=True)),
                ('pm10', models.BooleanField(default=True)),
                ('device', models.BooleanField()),
                ('master', models.CharField(choices=[('N', '无'), ('G', '组管理员'), ('S', '超级管理员')], max_length=3)),
                ('charge', models.ManyToManyField(to='emsys.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Usergroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=30, unique=True)),
                ('discri', models.CharField(max_length=80)),
                ('num', models.IntegerField()),
                ('tem', models.BooleanField(default=True)),
                ('hum', models.BooleanField(default=True)),
                ('pm25', models.BooleanField(default=True)),
                ('pm10', models.BooleanField(default=True)),
                ('device', models.BooleanField()),
                ('charge', models.ManyToManyField(to='emsys.Device')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emsys.Usergroup'),
        ),
    ]
