# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
